### ISSUE TITLE
ImportError: No module named cabot_alert_rocketchat

### ISSUE THREAD

**Issue by ferdousulhaque** [ObjectifLibre/cabot-alert-rocketchat#1]
I am getting the following error when I add the plugin in the cabot_alert_rocketchat. As per the web error it is saying for able to find module named cabot_alert_rocketchat. Can you please give a solution.

> CABOT_PLUGINS_ENABLED=cabot_alert_hipchat,cabot_alert_twilio,cabot_alert_email,cabot_alert_slack,cabot_alert_rocketchat

```
Traceback (most recent call last):
web_1       |   File "/usr/local/bin/cabot", line 11, in <module>
web_1       |     sys.exit(main())
web_1       |   File "/usr/local/lib/python2.7/site-packages/cabot/entrypoint.py", line 10, in main
web_1       |     execute_from_command_line(sys.argv)
web_1       |   File "/usr/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 364, in execute_from_command_line
web_1       |     utility.execute()
web_1       |   File "/usr/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 338, in execute
web_1       |     django.setup()
web_1       |   File "/usr/local/lib/python2.7/site-packages/django/__init__.py", line 27, in setup
web_1       |     apps.populate(settings.INSTALLED_APPS)
web_1       |   File "/usr/local/lib/python2.7/site-packages/django/apps/registry.py", line 85, in populate
web_1       |     app_config = AppConfig.create(entry)
web_1       |   File "/usr/local/lib/python2.7/site-packages/django/apps/config.py", line 94, in create
web_1       |     module = import_module(entry)
web_1       |   File "/usr/local/lib/python2.7/importlib/__init__.py", line 37, in import_module
web_1       |     __import__(name)
web_1       | ImportError: No module named cabot_alert_rocketchat
```

**Comment by fydrah** [comment]
Hi @ferdousulhaque,

How did you install (or upgrade you existing installation) with this plugin ?

Currently, there is a PR still in progress to add cabot_alert_rocketchat plugin to the plugin requirements of Cabot (https://github.com/arachnys/cabot/pull/622).

If you still need to install this plugin, you should update your requirements-plugins.txt just like this https://github.com/arachnys/cabot/pull/622/commits/af501dc707ea0e63bec220d549bfdbbfb43d6211#diff-7e8e0239ca7a68dd10a7606036d3e114R5

Regards,

**Comment by ferdousulhaque** [comment]
I managed to install the cabot-alert-rocketchat. Now the following error is not showing, however, now having another problem.

When rocket chat plugin in enabled, services are not able to check all. Always showing passing, while checking the logs I found this as below. While check is failed, still service is showing passing.

```
worker_1    | [2018-06-27 11:28:23,978: ERROR/MainProcess] Received unregistered task of type 'cabot.cabotapp.tasks.run_all_checks'.
worker_1    | The message has been ignored and discarded.
worker_1    | 
worker_1    | Did you remember to import the module containing this task?
worker_1    | Or maybe you're using relative imports?
worker_1    | 
worker_1    | Please see
worker_1    | http://docs.celeryq.org/en/latest/internals/protocol.html
worker_1    | for more information.
worker_1    | 
worker_1    | The full contents of the message body was:
worker_1    | u'[[], {}, {"chord": null, "callbacks": null, "errbacks": null, "chain": null}]' (77b)
worker_1    | Traceback (most recent call last):
worker_1    |   File "/usr/local/lib/python2.7/site-packages/celery/worker/consumer/consumer.py", line 559, in on_task_received
worker_1    |     strategy = strategies[type_]
worker_1    | KeyError: 'cabot.cabotapp.tasks.run_all_checks'
```

**Comment by fydrah** [comment]
Which version/tag of cabot app are you using ?
Can you also provide your configuration ?

**Comment by ferdousulhaque** [comment]
I am using https://github.com/cabotapp/docker-cabot with master branch.

**Comment by Zegorax** [comment]
Hello,

Can you post how you solved your last error ?

Thank you very much
